### ISSUE TITLE
elijah refactor todo

### ISSUE THREAD

**Issue by ecuber** [techtutorapp/techtutor#13]
things to change when refactoring code:

- [ ]  transition everything to typescript
- [ ] implement [gatsby image](https://www.gatsbyjs.com/docs/how-to/images-and-media/using-gatsby-image/)
- [ ] modernize UI
- [ ] responsiveness for mobile
- [ ] abstract away all layout components
- [ ] chakra theme

doing all this in one PR so that there can be a uniform and stable system for new contributors to be able to build onto instead of the current mess that the code is
